version: '3.9'

services:
  daily:
    container_name: daily
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres:5432/daily
      DB_USERNAME: daily
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_PROMPT: ${OPENAI_PROMPT}
      SERVER_USE_FORWARD_HEADERS: "true"
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: daily
      POSTGRES_USER: daily
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
